### ISSUE TITLE
Game now crashes on start up

### ISSUE THREAD

**Issue by iggyphoenix** [What42Pizza/Mindustry-Production-Mod#10]
Having just imported this mor and enabled it mindusty crashes on start up, it get to 68% then closes meaning I can disable the mod.

I'm an Android user

**Comment by What42Pizza** [comment]
Have you tried launching it again? Whenever I install it on my phone (which is also Android), it crashes the first time, but works fine after that. Also, I thought Mindustry disables mods that cause the game to crash, so it might not even be the mod. It's been a while since I've played Mindustry, so I could be wrong, though.
